### ISSUE TITLE
Filter non-images files in folder

### ISSUE THREAD

**Issue by attashe** [Storia-AI/image-eval#16]
System files inside the image folder cause an error
```
Traceback (most recent call last):
  File "/opt/..../bin/image_eval", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/..../site-packages/eval.py", line 132, in main
    generated_images = get_images_from_dir(args.generated_images)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.../site-packages/eval.py", line 104, in get_images_from_dir
    pil_image = Image.open(full_image_path).convert("RGB")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/.../PIL/Image.py", line 3236, in open
    fp = builtins.open(filename, "rb")
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
IsADirectoryError: [Errno 21] Is a directory: '/home/.../.ipynb_checkpoints'
```

**Comment by attashe** [comment]
This filter already implemented in `eval.py`. Command `pip install image-eval` install old versin.
Better use:
```
git clone https://github.com/Storia-AI/image-eval.git
cd image-eval
pip install -e .
```
But newer version need https://pypi.org/project/vendi-score/ . That could be installed with `pip install vendi-score`

**Comment by iuliaturc** [comment]
Thanks @attashe for the suggestions! We pushed a new version to pypi so `pip install image-eval` should work out of the box now.
